{"name": "Создание пользователя с существующей почтой", "status": "failed", "statusDetails": {"message": "AssertionError: assert (403 == 500)\n +  where 500 = <Response [500]>.status_code", "trace": "self = <tests.test_create_user.TestCreateUser object at 0x7fa931694580>\n\n    @allure.title('Создание пользователя с существующей почтой')\n    def test_create_two_same_user_error(self):\n        email, password, user = generate_data_new_user()\n        payload = {\n            'email': email,\n            'password': password,\n            'name': user\n        }\n    \n        response1 = requests.post('https://stellarburgers.nomoreparties.site/api/auth/register', data=payload)\n        response2 = requests.post('https://stellarburgers.nomoreparties.site/api/auth/register', data=payload)\n>       assert 403 == response2.status_code and response2[\"message\"] == 'User already exists'\nE       assert (403 == 500)\nE        +  where 500 = <Response [500]>.status_code\n\ntests/test_create_user.py:31: AssertionError"}, "start": 1707762470080, "stop": 1707762470896, "uuid": "3e1a712d-af96-44e0-9d55-054277cba464", "historyId": "89b89e8f483dce1027ccb84ef06c7c44", "testCaseId": "89b89e8f483dce1027ccb84ef06c7c44", "fullName": "tests.test_create_user.TestCreateUser#test_create_two_same_user_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "sam-IdeaPad-Gaming-3-15IHU6"}, {"name": "thread", "value": "5520-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}